Rotation status property of block added.
Padam87/bin-packer pull request #9
Opened 2023-08-31 14:27 UTC by gstankov

Hey,

made a proposed change to the 'Block' model to include rotation status of a block.

Can you please verify? 

Br,

2023-08-31 16:00 UTC, Padam87 requested changes

2023-08-31 16:00 UTC, Padam87 commented on src/Model/Block.php
> +        $this->rotated = true;
`$this->rotated = !$this->rotated;`

I'd just negate it. That way, if rotate is called multiple times for some reason, we still know which is the original.

2023-08-31 16:00 UTC, Padam87 commented on src/Model/Block.php
A getter is also needed. `isRotated`

2023-09-01 06:10 UTC, gstankov commented
Ok, made the changes.

Also I wanted to write a test case for it but couldn't run them. Getting some errors regarding 'PHPUnit' framework.

What's the correct command to run them? Tried 'phpunit --bootstrap ./vendor/autoload.php tests' with no success.

Br,

2023-09-01 13:27 UTC, Padam87 commented
I just ran phpunit without parameters, it picked up the `phpunit.xml.dist` file as it should.

2023-09-05 07:10 UTC, gstankov reviewed
Hi Adam,

i managed to create and run a test. Can you please take a look.

Thanks in advance, br

2023-09-05 16:46 UTC, merged